name: "Archive"
description: "Xcode Archive and generate xcframeworks"
inputs:
  build-configuration:
    description: "Build configuration of Xcode, either Debug or Release"
    required: true
    default: Release
runs:
  using: "composite"
  steps:
    - name: "echo ${{ inputs.build-configuration }}"
      shell: bash
      run: echo ${{ inputs.build-configuration }}
    - name: Archive
      shell: bash
      run: |
        echo inputs.build-configuration: "{{ inputs.build-configuration }}"
        make CONFIGURATION="${{ inputs.build-configuration }}" archive
