name: "Archive"
description: "Xcode Archive and generate xcframeworks"
inputs:
  build-configuration:
    description: "Build configuration of Xcode, either Debug or Release"
    required: true
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - name: "echo ${{ inputs.build-configuration }}"
      shell: bash
      run: echo ${{ inputs.build-configuration }}
    - name: Archive
      shell: bash
      run: |
        echo inputs.build-configuration: "{{ inputs.build-configuration }}"
        make CONFIGURATION="${{ inputs.build-configuration }}" archive
