name: "Archive"
description: "Xcode Archive and generate xcframeworks"
inputs:
  xcode-configuration:
    description: "Build configuration of Xcode, either Debug or Release"
    required: true
    default: Release
runs:
  using: "composite"
  steps:
    - name: "echo ${{ inputs.xcode-configuration }}"
      shell: bash
      run: echo ${{ inputs.xcode-configuration }}
    - name: Archive
      shell: bash
      run: |
        echo inputs.xcode-configuration: "{{ inputs.xcode-configuration }}"
        make CONFIGURATION="${{ inputs.xcode-configuration }}" archive
