name: "Archive Platform"
description: "Xcode Archive single platform"
inputs:
  xcode-configuration:
    description: "Build configuration of Xcode, either Debug or Release"
    required: true
    default: Release
  platform:
    description: "Apple platform, either iphonesimulator, iphoneos, or maccatalyst"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/setup
      name: Setup
      with:
        xcode-configuration: ${{ inputs.xcode-configuration }}

    - name: Archive
      shell: bash
      run: |
        make CONFIGURATION="${{ inputs.xcode-configuration }}" PLATFORM="${{ inputs.platform }}" archive-platform

    - name: Upload to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.platform }}-binary-${{ inputs.xcode-configuration }}"
        path: "${{ inputs.platform }}-binary-${{ inputs.xcode-configuration }}.tar.gz"
