name: "Archive Platform"
description: "Xcode Archive single platform"
inputs:
  platform:
    description: "Apple platform, either iphonesimulator, iphoneos, or maccatalyst"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/setup
      name: Setup

    - name: Archive
      shell: bash
      run: |
        cd ios
        echo "before compile:"
        ccache --show-stats -v
        make CONFIGURATION="Debug" PLATFORM="${{ inputs.platform }}" archive-platform
        make CONFIGURATION="Release" PLATFORM="${{ inputs.platform }}" archive-platform
        echo "ccache stats:"
        ccache --show-stats -v

    - name: Upload to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.platform }}-binary-Debug"
        path: "${{ inputs.platform }}-binary-Debug.tar.gz"

    - name: Upload to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.platform }}-binary-Release"
        path: "${{ inputs.platform }}-binary-Release.tar.gz"
